### ISSUE TITLE
thumbnails and .xml files

### ISSUE THREAD

**Issue by Rokinluohhh** [PerrySkywalker/TransMIL-visualisation#1]
Is thumbnails from Stiches after creat_feaure_fp.py? And Where .xml files from? Looking forward to your reply,thans a lot!

**Comment by PerrySkywalker** [comment]
> Is thumbnails from Stiches after creat_feaure_fp.py? And Where .xml files from? Looking forward to your reply,thans a lot!

Yes, you can use the thumbnails from Stiches after create__patch_fp.py, and the .xml files is the annotation from the camelyon16.
No matter how you generate the thumbnails, you just need to make sure that their multiplicity is related to each other.

**Comment by PerrySkywalker** [comment]
> Is thumbnails from Stiches after creat_feaure_fp.py? And Where .xml files from? Looking forward to your reply,thans a lot!

In demo.jpg, the black line is the annotation for camelyon16, and the green line is the foreground area obtained using CLAM.

**Comment by Rokinluohhh** [comment]
就是我用的是TCGA的数据，那我是不是也是得用TCGA的XML文件呢

**Comment by PerrySkywalker** [comment]
> 就是我用的是TCGA的数据，那我是不是也是得用TCGA的XML文件呢
xml只是我为了展示官方标注，要是官方有标注你画上去就行，没有就别画了，camelyon16有所以我想对比一下我生成的是否正确。
