### ISSUE TITLE
when patch_size=256,how to set the parameters?

### ISSUE THREAD

**Issue by YAOSL98** [PerrySkywalker/TransMIL-visualisation#2]
A good job! It's very useful for my experiments. But my patch_size=256, and there is an error, how to resolve it? Thanks a lot![屏幕截图 2024-03-27 151042](https://github.com/PerrySkywalker/TransMIL-visualisation/assets/68221964/c22726c1-41bb-4024-9e68-7e7a16d4e10d)

**Comment by YAOSL98** [comment]
I know where I went wrong. I should have used the h5 file generated by extract_features_fp.py instead of the file generated by create_patches_fp.py.

**Comment by PerrySkywalker** [comment]
> I know where I went wrong. I should have used the h5 file generated by extract_features_fp.py instead of the file generated by create_patches_fp.py.

Yes, you need to use the h5 files come from extract_features_fp.py.
