### ISSUE TITLE
关于热力图处理

### ISSUE THREAD

**Issue by Jiaxuan777** [PerrySkywalker/TransMIL-visualisation#3]
请问为什么在处理mask矩阵的时候，没有先归一化，而是直接进行了np.uint8(mask * 255)这样的操作，然而我在前面加了归一化，反倒出现了很差的结果，最终的heatmap的值都是一样的了，这步操作的原理是什么呢。如果mask矩阵中的最大值远远超过了255，而非0到1之间，那直接乘255这步岂不是会造成截断

**Comment by Liu-jiuxuan** [comment]
![1](https://github.com/PerrySkywalker/TransMIL-visualisation/assets/57988331/5734128e-df78-4741-a63b-a9748435408b)

**Comment by PerrySkywalker** [comment]
> 请问为什么在处理mask矩阵的时候，没有先归一化，而是直接进行了np.uint8(mask * 255)这样的操作，然而我在前面加了归一化，反倒出现了很差的结果，最终的heatmap的值都是一样的了，这步操作的原理是什么呢。如果mask矩阵中的最大值远远超过了255，而非0到1之间，那直接乘255这步岂不是会造成截断

 我刚开始也是这样，得到注意力的值都是非常小的，你看我的代码，其实我是除以了所有patch的均值的0.8倍，这个0.8是自己调出来的，你自己试试。超出1到无所谓uint8最大到255，超过了也会被截断把，应该是这样。

**Comment by PerrySkywalker** [comment]
> 请问为什么在处理mask矩阵的时候，没有先归一化，而是直接进行了np.uint8(mask * 255)这样的操作，然而我在前面加了归一化，反倒出现了很差的结果，最终的heatmap的值都是一样的了，这步操作的原理是什么呢。如果mask矩阵中的最大值远远超过了255，而非0到1之间，那直接乘255这步岂不是会造成截断

255很红
