### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by Rokinluohhh** [PerrySkywalker/TransMIL-visualisation#4]
为啥这个需要这么大的内存
![微信图片_20240407161110](https://github.com/PerrySkywalker/TransMIL-visualisation/assets/131835675/bb26e48c-2517-4bbf-a415-ef8c3edec7b2)

**Comment by PerrySkywalker** [comment]
这个我也在想，假如你输入的特征尺寸是10000x512那么两层的MHSA，那么输出的尺寸为10000 x 10000 x 16，这个是个非常大的数字，和特征的数量是平方倍关系，我建议把特征数量特别大的片子先别可视化。我最近有时间会优化这个东西。

**Comment by PerrySkywalker** [comment]
> 为啥这个需要这么大的内存 ![微信图片_20240407161110](https://private-user-images.githubusercontent.com/131835675/320262788-bb26e48c-2517-4bbf-a415-ef8c3edec7b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzkzNTYsIm5iZiI6MTcxMjQ3OTA1NiwicGF0aCI6Ii8xMzE4MzU2NzUvMzIwMjYyNzg4LWJiMjZlNDhjLTI1MTctNGJiZi1hNDE1LWVmOGMzZWRlYzdiMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwODM3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTVkODc3ZWE5YTcxOGM5ZTAyODA1YzIzMTRkZGQ1MGExOGM4NjJhNDViYmM2OWIzMjAxYTU4MWUyNGEyMDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KVRETwH6QbVomo333k1x32R6f5ee2WTQ0hW2Zul8vfg)



> 为啥这个需要这么大的内存 ![微信图片_20240407161110](https://private-user-images.githubusercontent.com/131835675/320262788-bb26e48c-2517-4bbf-a415-ef8c3edec7b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzkzNTYsIm5iZiI6MTcxMjQ3OTA1NiwicGF0aCI6Ii8xMzE4MzU2NzUvMzIwMjYyNzg4LWJiMjZlNDhjLTI1MTctNGJiZi1hNDE1LWVmOGMzZWRlYzdiMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwODM3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTVkODc3ZWE5YTcxOGM5ZTAyODA1YzIzMTRkZGQ1MGExOGM4NjJhNDViYmM2OWIzMjAxYTU4MWUyNGEyMDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KVRETwH6QbVomo333k1x32R6f5ee2WTQ0hW2Zul8vfg)

加我wx wmk1115384863
