### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by YAOSL98** [PerrySkywalker/TransMIL-visualisation#5]
经常出现cuda out of memory（当pt文件大于100M）请问是否可以优化一下，谢谢您的工作

**Comment by PerrySkywalker** [comment]
请问你使用的是什么显卡，以及特征的数量是多少？

**Comment by YAOSL98** [comment]
您好！您发给我的信件已经收到,我将尽快处理

**Comment by PerrySkywalker** [comment]
我在本地测试24G的显存，20w个特征是没问题的，2层MHSA
