### ISSUE TITLE
关于Yhat不等于1

### ISSUE THREAD

**Issue by Jiaxuan777** [PerrySkywalker/TransMIL-visualisation#6]
请问这部分代码目的是什么呀，似乎有一些问题

**Comment by PerrySkywalker** [comment]
> 请问这部分代码目的是什么呀，似乎有一些问题

哪一部分？

**Comment by Jiaxuan777** [comment]
![微信截图_20240611170446](https://github.com/PerrySkywalker/TransMIL-visualisation/assets/57988331/5f75cc44-7f85-46ac-84eb-89e47114518f)

**Comment by PerrySkywalker** [comment]
> ![微信截图_20240611170446](https://private-user-images.githubusercontent.com/57988331/338515603-5f75cc44-7f85-46ac-84eb-89e47114518f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTgyNjcsIm5iZiI6MTcxODA5Nzk2NywicGF0aCI6Ii81Nzk4ODMzMS8zMzg1MTU2MDMtNWY3NWNjNDQtN2Y4NS00NmFjLTg0ZWItODllNDcxMTQ1MThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA5MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NTIyMTg5ZmFjODM0ZmZmNjc4MzljMTBhZWE1ZmFlZWQ5ODUwMjkwYjQ5MThlMjBlNjI0YzY0ODAwM2UxYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oc1n4l_dgszIOPM5MbBS1nbo2oKMSzhn9QBMmVG4lFw)
已修改，直接注释掉attns = attns.max()
