### ISSUE TITLE
image目录

### ISSUE THREAD

**Issue by cvnlpHjb** [PerrySkywalker/TransMIL-visualisation#7]
您好，打扰了，image目录下面的图片是哪里得到的呢？谢谢回复

**Comment by PerrySkywalker** [comment]
使用openslide就可以获取缩率图，或者你使用clam进行切块 --seg --patch --stitch加上这几个参数

**Comment by cvnlpHjb** [comment]
> 使用openslide就可以获取缩率图，或者你使用clam进行切块 --seg --patch --stitch加上这几个参数

您好，缩略图我用的clam第一步mask下面的jpg文件，然后用我自己的模型和参数，画图效果不好是为什么呢，谢谢回复

**Comment by PerrySkywalker** [comment]
> > 使用openslide就可以获取缩率图，或者你使用clam进行切块 --seg --patch --stitch加上这几个参数
> 
> 您好，缩略图我用的clam第一步mask下面的jpg文件，然后用我自己的模型和参数，画图效果不好是为什么呢，谢谢回复
效果不好是正常的，换个特征提取器试试，比如UNI、CONCH之类的。
