### ISSUE TITLE
class_token attention ?

### ISSUE THREAD

**Issue by xushenkun** [PerrySkywalker/TransMIL-visualisation#8]
Thank you for the wonderful work!

The question is:
Why attn1 = (attn1 @ attn2_inv)[:,:,1,:].unsqueeze(dim=2)
not: attn1 = (attn1 @ attn2_inv)[:,:,-n:-n+1,:]

because padding in NystromAttention is x = F.pad(x, (0, 0, padding, 0), value = 0), which the class_token at [:,:,-n:-n+1,:]

**Comment by PerrySkywalker** [comment]
Yes, you are right. Thank you, I've fixed the bug.
